# Generated by Django 6.0.3 on 2026-04-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="condition",
            field=models.CharField(
                choices=[
                    ("excellent", "Отличное"),
                    ("good", "Хорошее"),
                    ("satisfactory", "Удовлетворительное"),
                ],
                max_length=20,
            ),
        ),
    ]
