# Generated by Django 6.0.3 on 2026-06-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_application_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='trade_in_certificate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='trade_in_item_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
