# Generated by Django 6.0.3 on 2026-04-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personaldata",
            name="payment_details",
        ),
        migrations.AddField(
            model_name="personaldata",
            name="account_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="personaldata",
            name="bank_name",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="personaldata",
            name="bik",
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name="personaldata",
            name="correspondent_account",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
