# Generated by Django 6.0.3 on 2026-09-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_application_trade_in_certificate_amount_and_more"),
        ("offers", "0002_remove_personaldata_payment_details_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("purchase", "Выкуп"),
                            ("trade_in", "Trade-In"),
                            ("commission", "Реализация"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_prices",
                        to="applications.applicationitem",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="offers.offer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена в предложении",
                "verbose_name_plural": "Цены в предложении",
                "db_table": "offer_prices",
                "unique_together": {("offer", "item", "format")},
            },
        ),
    ]
