# Generated by Django 6.0.3 on 2026-04-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="contract_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
