# Generated by Django 6.0.3 on 2026-05-28 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_remove_application_brand_and_more"),
        (
            "contracts",
            "0003_remove_smscode_contract_document_smscode_document_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("application", "document_type")},
        ),
    ]
